### ISSUE TITLE
Write a description for /unregister

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/study-bot#5]
Please write a improved description for the /unregister command

[See this file](https://github.com/CarletonComputerScienceSociety/study-bot/blob/e7dc305d516ad871bba18d5e0114556b8f88c2c7/lib/discord/commands/unregister.js)

**Comment by jackricketts** [comment]
If you decide to reregister after unregistering, will the bot store information previously entered?

**Comment by d-loree** [comment]
🥳

**Comment by a-linco** [comment]
Forgot to mention, but I created a pull request for this which was merged into the main

**Comment by Jace222** [comment]
Closed in #21
